general:
  print-unset-entity: true
  print-unset-cause: true

events:
  pre-process: |-
    if perm "itsdeath.keepinv" then {
      true
    } else {
      false
    }
  post-process: [ ]
  after-respawn: |-
    sound ITEM.SHIELD.BLOCK
    title inline "§3重生成功, §2{{ sender }}!" subtitle "§7珍爱生命, 远离死亡." by 10 40 10
  after-retrieve: |-
    sound ITEM.BOTTLE.FILL
    title "§a§l索取成功" by 10 40 10

worlds:
  world:
    # ALL -> 掉落全部物品
    # KEEP -> 不掉落物品
    # int -> 随机掉落多少格子的物品
    item-drop: ALL
    # 掉落多少经验
    # 0 -> 不掉落经验
    # -1 -> 按照原版算法
    exp-drop: 0.75
    expire: 3h
  world_nether:
    item-drop: ALL
    exp-drop: 0.5
    expire: 3h
  world_the_end:
    item-drop: ALL
    exp-drop: 0.25
    message: SERVER
    expire: 3h
  spawn:
    item-drop: KEEP
    exp-drop: 0
    expire: 1m
